// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gkzcbrcxclkqwhebnxvo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdremNicmN4Y2xrcXdoZWJueHZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNTUyMDQsImV4cCI6MjA2MDkzMTIwNH0.6fw0tUxYuAfaXGxa6OZlREpep3dYPnM6hB7aniQl02k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);